# Form implementation generated from reading ui file 'pause_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_pauseWidget(object):
    def setupUi(self, pauseWidget):
        pauseWidget.setObjectName("pauseWidget")
        pauseWidget.resize(532, 281)
        self.widget = QtWidgets.QWidget(pauseWidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 532, 281))
        self.widget.setStyleSheet("background-color: rgba(34, 31, 31, 0.6);\n"
"border-radius:40px;")
        self.widget.setObjectName("widget")
        self.continueButton = QtWidgets.QPushButton(self.widget)
        self.continueButton.setGeometry(QtCore.QRect(300, 170, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.continueButton.setFont(font)
        self.continueButton.setStyleSheet("background-color: rgb(251, 95, 56);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./window/icons/play.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.continueButton.setIcon(icon)
        self.continueButton.setIconSize(QtCore.QSize(30, 30))
        self.continueButton.setObjectName("continueButton")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(90, 170, 150, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-color: rgb(49, 51, 55);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:30px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./window/icons/exit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exitButton.setIcon(icon1)
        self.exitButton.setIconSize(QtCore.QSize(25, 25))
        self.exitButton.setObjectName("exitButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(220, 60, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(130, 50, 91, 81))
        self.widget_2.setStyleSheet("image: url(:/window/icons/pause.svg);\n"
"border-radius:0;\n"
"background-color:transparent;")
        self.widget_2.setObjectName("widget_2")

        self.retranslateUi(pauseWidget)
        QtCore.QMetaObject.connectSlotsByName(pauseWidget)

    def retranslateUi(self, pauseWidget):
        _translate = QtCore.QCoreApplication.translate
        pauseWidget.setWindowTitle(_translate("pauseWidget", "Form"))
        self.continueButton.setText(_translate("pauseWidget", " 继续"))
        self.exitButton.setText(_translate("pauseWidget", " 退出"))
        self.label.setText(_translate("pauseWidget", "暂 停"))
