# Form implementation generated from reading ui file 'index_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Index_Window(object):
    def setupUi(self, Index_Window):
        Index_Window.setObjectName("Index_Window")
        Index_Window.resize(1078, 681)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./window/icons/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Index_Window.setWindowIcon(icon)
        Index_Window.setStyleSheet("background-color: rgb(248, 248, 248);\n"
"outline:none;")
        self.centralwidget = QtWidgets.QWidget(Index_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(230, 16777215))
        self.widget.setStyleSheet("/*background-color: rgb(248,248,248);*/\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setMinimumSize(QtCore.QSize(50, 50))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setStyleSheet("border-image: url(./window/icons/user_index.svg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nickname_Label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.nickname_Label.setFont(font)
        self.nickname_Label.setStyleSheet("")
        self.nickname_Label.setText("")
        self.nickname_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nickname_Label.setObjectName("nickname_Label")
        self.horizontalLayout_2.addWidget(self.nickname_Label)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 7)
        self.verticalLayout.addWidget(self.widget_2)
        self.pageListWidget = QtWidgets.QListWidget(self.widget)
        self.pageListWidget.setMinimumSize(QtCore.QSize(0, 340))
        self.pageListWidget.setStyleSheet("QListWidget {\n"
"    qproperty-iconSize: 25px 25px;\n"
"     color: Black;\n"
"    padding-top:20px;\n"
"}\n"
"\n"
"QListWidget::Item{\n"
"    color: rgb(129, 131, 133);\n"
"    height: 75px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    margin-top:5px;\n"
"}\n"
"\n"
"QListWidget::Item:hover {\n"
"    background-color: rgb(237, 244, 255);\n"
"    border-right: 5px solid rgb(60, 133, 242);\n"
"    padding-left:10px;\n"
"}\n"
"\n"
"QListWidget::Item:selected {\n"
"    background-color: rgb(237, 244, 255);\n"
"    border-right: 5px solid rgb(60, 133, 242);\n"
"    color:rgb(60, 133, 242);\n"
"    padding-left:10px;\n"
"}")
        self.pageListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.pageListWidget.setUniformItemSizes(True)
        self.pageListWidget.setObjectName("pageListWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./window/icons/home.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon1)
        self.pageListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./window/icons/yl.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon2)
        self.pageListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./window/icons/history.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon3)
        self.pageListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        item.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./window/icons/settings.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon4)
        self.pageListWidget.addItem(item)
        self.verticalLayout.addWidget(self.pageListWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 246, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.exitButton = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(30, 60))
        self.exitButton.setMaximumSize(QtCore.QSize(190, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.exitButton.setFont(font)
        self.exitButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.exitButton.setStyleSheet("QPushButton{\n"
"    color: rgb(127,127,138);\n"
"    text-align: left;\n"
"    padding-left:10px;\n"
"    border-radius:0;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 205, 210);\n"
"    border-right: 5px solid rgb(244, 67, 54);\n"
"    color: rgb(244, 67, 54);\n"
"    padding-left:20px;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./window/icons/exit_gray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exitButton.setIcon(icon5)
        self.exitButton.setIconSize(QtCore.QSize(20, 20))
        self.exitButton.setCheckable(False)
        self.exitButton.setChecked(False)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_4.raise_()
        self.pageListWidget.raise_()
        self.widget_2.raise_()
        self.horizontalLayout.addWidget(self.widget)
        self.pageStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.pageStackedWidget.setObjectName("pageStackedWidget")
        self.indexPage = QtWidgets.QWidget()
        self.indexPage.setStyleSheet("")
        self.indexPage.setObjectName("indexPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.indexPage)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_16 = QtWidgets.QWidget(self.indexPage)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_16)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_11 = QtWidgets.QLabel(self.widget_16)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("/*color: rgb(129, 131, 133);*/")
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.indexPage)
        self.widget_17.setStyleSheet("image: url(./window/icons/dog.svg);")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_8.addWidget(self.widget_17)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 9)
        self.pageStackedWidget.addWidget(self.indexPage)
        self.historyPage = QtWidgets.QWidget()
        self.historyPage.setStyleSheet("")
        self.historyPage.setObjectName("historyPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.historyPage)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_18 = QtWidgets.QWidget(self.historyPage)
        self.widget_18.setObjectName("widget_18")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_18)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_12 = QtWidgets.QLabel(self.widget_18)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("/*color: rgb(129, 131, 133);*/")
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.historyPage)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_3 = QtWidgets.QWidget(self.widget_19)
        self.widget_3.setStyleSheet("#widget_3{\n"
"    border-radius:10px;\n"
"    padding:20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_5.setStyleSheet("#widget_5{\n"
"    border-bottom:1px solid rgb(189, 189, 189);\n"
"    background-color: transparent;\n"
"}")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent;\n"
"padding-left:2px;")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.history_sport_groupBox = QtWidgets.QGroupBox(self.widget_5)
        self.history_sport_groupBox.setStyleSheet("#history_sport_groupBox{\n"
"    padding:0px;\n"
"    border:0px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QPushButton{\n"
"    height:50px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"    border:1px solid rgb(189, 189, 189);\n"
"}\n"
"QPushButton::checked {\n"
"    background-color: rgb(50, 191, 209);\n"
"    color: rgb(255, 255, 255);\n"
"    border:1px solid rgb(50, 191, 209);\n"
"}")
        self.history_sport_groupBox.setTitle("")
        self.history_sport_groupBox.setObjectName("history_sport_groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.history_sport_groupBox)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setHorizontalSpacing(6)
        self.gridLayout_10.setVerticalSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.history_query_squat_pushButton = QtWidgets.QPushButton(self.history_sport_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_query_squat_pushButton.setFont(font)
        self.history_query_squat_pushButton.setCheckable(True)
        self.history_query_squat_pushButton.setAutoExclusive(True)
        self.history_query_squat_pushButton.setObjectName("history_query_squat_pushButton")
        self.gridLayout_10.addWidget(self.history_query_squat_pushButton, 0, 2, 1, 1)
        self.history_query_dumbbell_pushButton = QtWidgets.QPushButton(self.history_sport_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_query_dumbbell_pushButton.setFont(font)
        self.history_query_dumbbell_pushButton.setCheckable(True)
        self.history_query_dumbbell_pushButton.setAutoExclusive(True)
        self.history_query_dumbbell_pushButton.setObjectName("history_query_dumbbell_pushButton")
        self.gridLayout_10.addWidget(self.history_query_dumbbell_pushButton, 2, 2, 1, 1)
        self.history_query_push_pushButton = QtWidgets.QPushButton(self.history_sport_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_query_push_pushButton.setFont(font)
        self.history_query_push_pushButton.setCheckable(True)
        self.history_query_push_pushButton.setAutoExclusive(True)
        self.history_query_push_pushButton.setObjectName("history_query_push_pushButton")
        self.gridLayout_10.addWidget(self.history_query_push_pushButton, 0, 1, 1, 1)
        self.history_query_all_pushButton = QtWidgets.QPushButton(self.history_sport_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_query_all_pushButton.setFont(font)
        self.history_query_all_pushButton.setCheckable(True)
        self.history_query_all_pushButton.setChecked(True)
        self.history_query_all_pushButton.setAutoExclusive(True)
        self.history_query_all_pushButton.setObjectName("history_query_all_pushButton")
        self.gridLayout_10.addWidget(self.history_query_all_pushButton, 0, 0, 1, 1)
        self.history_query_jumpingJacks_pushButton = QtWidgets.QPushButton(self.history_sport_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_query_jumpingJacks_pushButton.setFont(font)
        self.history_query_jumpingJacks_pushButton.setCheckable(True)
        self.history_query_jumpingJacks_pushButton.setAutoExclusive(True)
        self.history_query_jumpingJacks_pushButton.setObjectName("history_query_jumpingJacks_pushButton")
        self.gridLayout_10.addWidget(self.history_query_jumpingJacks_pushButton, 2, 1, 1, 1)
        self.history_query_chinning_pushButton = QtWidgets.QPushButton(self.history_sport_groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_query_chinning_pushButton.setFont(font)
        self.history_query_chinning_pushButton.setCheckable(True)
        self.history_query_chinning_pushButton.setAutoExclusive(True)
        self.history_query_chinning_pushButton.setObjectName("history_query_chinning_pushButton")
        self.gridLayout_10.addWidget(self.history_query_chinning_pushButton, 2, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.history_sport_groupBox)
        self.verticalLayout_10.addWidget(self.widget_5)
        self.widget_20 = QtWidgets.QWidget(self.widget_3)
        self.widget_20.setStyleSheet("#widget_20{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-bottom:1px solid rgb(189, 189, 189);\n"
"}")
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_12.setContentsMargins(2, 7, 2, 0)
        self.verticalLayout_12.setSpacing(15)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.widget_20)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin-left:2px;\n"
"margin-bottom: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.history_calendarWidget = QtWidgets.QCalendarWidget(self.widget_20)
        self.history_calendarWidget.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.history_calendarWidget.setStyleSheet("QToolButton{\n"
"    height: 20px;\n"
"}\n"
"\n"
"QToolButton#qt_calendar_monthbutton {\n"
"    background-color: rgb(50, 191, 209);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_yearbutton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color: rgb(50, 191, 209);\n"
"}\n"
"\n"
"#qt_calendar_navigationbar {\n"
"    background-color: rgb(50, 191, 209);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_prevmonth {\n"
"    background-color: rgb(50, 191, 209);\n"
"    qproperty-icon:url(./window/icons/arrow_left.svg);\n"
"}\n"
"\n"
"QToolButton#qt_calendar_nextmonth {\n"
"    background-color: rgb(50, 191, 209);\n"
"    qproperty-icon:url(./window/icons/arrow_right.svg)\n"
"}\n"
"\n"
"QCalendarWidget QWidget {\n"
"    alternate-background-color: rgb(232, 231, 227);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.history_calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SelectionMode.SingleSelection)
        self.history_calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.ISOWeekNumbers)
        self.history_calendarWidget.setNavigationBarVisible(True)
        self.history_calendarWidget.setDateEditEnabled(True)
        self.history_calendarWidget.setObjectName("history_calendarWidget")
        self.verticalLayout_12.addWidget(self.history_calendarWidget)
        self.verticalLayout_10.addWidget(self.widget_20)
        self.widget_21 = QtWidgets.QWidget(self.widget_3)
        self.widget_21.setStyleSheet("QWidget{\n"
"    background-color:transparent;\n"
"    /*border-top:1px solid rgb(189, 189, 189);*/\n"
"    margin-top: 20px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(50, 191, 209);\n"
"    height: 45px;\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.history_reset_pushButton = QtWidgets.QPushButton(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_reset_pushButton.setFont(font)
        self.history_reset_pushButton.setObjectName("history_reset_pushButton")
        self.horizontalLayout_8.addWidget(self.history_reset_pushButton)
        self.history_sift_pushButton = QtWidgets.QPushButton(self.widget_21)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.history_sift_pushButton.setFont(font)
        self.history_sift_pushButton.setObjectName("history_sift_pushButton")
        self.horizontalLayout_8.addWidget(self.history_sift_pushButton)
        self.verticalLayout_10.addWidget(self.widget_21)
        spacerItem1 = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_7.addWidget(self.widget_3)
        self.historyListWidget = QtWidgets.QListWidget(self.widget_19)
        self.historyListWidget.setStyleSheet("QListWidget{\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListWidget::Item:hover {\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QListWidget::Item:selected {\n"
"    border-radius:5px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.historyListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.historyListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.historyListWidget.setObjectName("historyListWidget")
        self.horizontalLayout_7.addWidget(self.historyListWidget)
        self.horizontalLayout_7.setStretch(0, 4)
        self.horizontalLayout_7.setStretch(1, 6)
        self.verticalLayout_9.addWidget(self.widget_19)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 9)
        self.pageStackedWidget.addWidget(self.historyPage)
        self.sportPage = QtWidgets.QWidget()
        self.sportPage.setObjectName("sportPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sportPage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_6 = QtWidgets.QWidget(self.sportPage)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("/*color: rgb(129, 131, 133);*/")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.sportPage)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_12 = QtWidgets.QWidget(self.widget_7)
        self.widget_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.itemGroupBox = QtWidgets.QGroupBox(self.widget_12)
        self.itemGroupBox.setStyleSheet("#groupBox{\n"
"    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: rgb(248, 248, 248);\n"
"    min-height:130px;\n"
"    font-size:25px;\n"
"    text-align: center;\n"
"    margin:5px;\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover {\n"
"    margin:0px;\n"
"}\n"
"\n"
"QPushButton::checked {\n"
"    background-color: rgb(76, 175, 80);\n"
"    margin:0px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.itemGroupBox.setTitle("")
        self.itemGroupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.itemGroupBox.setObjectName("itemGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.itemGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushChoice_Button = QtWidgets.QPushButton(self.itemGroupBox)
        self.pushChoice_Button.setCheckable(True)
        self.pushChoice_Button.setChecked(True)
        self.pushChoice_Button.setAutoExclusive(True)
        self.pushChoice_Button.setObjectName("pushChoice_Button")
        self.gridLayout_5.addWidget(self.pushChoice_Button, 0, 0, 1, 1)
        self.chinningChoiceButton = QtWidgets.QPushButton(self.itemGroupBox)
        self.chinningChoiceButton.setCheckable(True)
        self.chinningChoiceButton.setAutoExclusive(True)
        self.chinningChoiceButton.setObjectName("chinningChoiceButton")
        self.gridLayout_5.addWidget(self.chinningChoiceButton, 0, 2, 1, 1)
        self.dumbbellChoiceButton = QtWidgets.QPushButton(self.itemGroupBox)
        self.dumbbellChoiceButton.setCheckable(True)
        self.dumbbellChoiceButton.setAutoExclusive(True)
        self.dumbbellChoiceButton.setObjectName("dumbbellChoiceButton")
        self.gridLayout_5.addWidget(self.dumbbellChoiceButton, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.itemGroupBox)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setAutoExclusive(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.itemGroupBox)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setAutoExclusive(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 2, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.itemGroupBox)
        self.pushButton_10.setEnabled(False)
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setAutoExclusive(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.itemGroupBox)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setAutoExclusive(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 2, 2, 1, 1)
        self.squatChoice_Button = QtWidgets.QPushButton(self.itemGroupBox)
        self.squatChoice_Button.setCheckable(True)
        self.squatChoice_Button.setAutoExclusive(True)
        self.squatChoice_Button.setObjectName("squatChoice_Button")
        self.gridLayout_5.addWidget(self.squatChoice_Button, 0, 1, 1, 1)
        self.jumpingJacksChoice_Button = QtWidgets.QPushButton(self.itemGroupBox)
        self.jumpingJacksChoice_Button.setCheckable(True)
        self.jumpingJacksChoice_Button.setAutoExclusive(True)
        self.jumpingJacksChoice_Button.setObjectName("jumpingJacksChoice_Button")
        self.gridLayout_5.addWidget(self.jumpingJacksChoice_Button, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.itemGroupBox)
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setStyleSheet("")
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.leftTime_Label = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.leftTime_Label.setFont(font)
        self.leftTime_Label.setObjectName("leftTime_Label")
        self.horizontalLayout_4.addWidget(self.leftTime_Label)
        spacerItem3 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.sportTime_Slider = QtWidgets.QSlider(self.widget_13)
        self.sportTime_Slider.setMinimumSize(QtCore.QSize(0, 24))
        self.sportTime_Slider.setStyleSheet("\n"
"QSlider::groove:horizontal {\n"
"border: 0px solid #bbb;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"background: rgb(235,97,0);\n"
"border-radius: 0px;\n"
"margin-top:8px;\n"
"margin-bottom:8px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"background: ;\n"
"    background-color: rgb(147, 147, 147);\n"
"border: 0px solid #777;\n"
"border-radius: 2px;\n"
"margin-top:8px;\n"
"margin-bottom:8px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"background: rgb(255,153,102);\n"
"border: 1px solid rgb(255,153,102);\n"
"width: 14px;\n"
"height:10px;\n"
"border-radius: 7px;\n"
"margin-top:2px;\n"
"margin-bottom:2px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"background: rgb(255,128,6);\n"
"border: 1px solid rgba(102,102,102,102);\n"
"border-radius: 7px;\n"
"}\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}")
        self.sportTime_Slider.setMinimum(10)
        self.sportTime_Slider.setMaximum(600)
        self.sportTime_Slider.setSingleStep(5)
        self.sportTime_Slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sportTime_Slider.setObjectName("sportTime_Slider")
        self.horizontalLayout_4.addWidget(self.sportTime_Slider)
        spacerItem4 = QtWidgets.QSpacerItem(164, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_7.addWidget(self.widget_13)
        self.verticalLayout_7.setStretch(0, 8)
        self.verticalLayout_7.setStretch(1, 2)
        self.horizontalLayout_3.addWidget(self.widget_12)
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setStyleSheet("#widget_8{\n"
"    /*border:2px solid rgb(129, 131, 133);*/\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(20, 64, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem5)
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setStyleSheet("background-color: transparent;")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.item_Label = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.item_Label.setFont(font)
        self.item_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.item_Label.setObjectName("item_Label")
        self.verticalLayout_5.addWidget(self.item_Label)
        self.verticalLayout_4.addWidget(self.widget_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_10.setStyleSheet("background-color: transparent;")
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.rightTime_Label = QtWidgets.QLabel(self.widget_10)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.rightTime_Label.setFont(font)
        self.rightTime_Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rightTime_Label.setObjectName("rightTime_Label")
        self.verticalLayout_6.addWidget(self.rightTime_Label)
        self.verticalLayout_4.addWidget(self.widget_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.widget_11 = QtWidgets.QWidget(self.widget_8)
        self.widget_11.setStyleSheet("background-color: transparent;")
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.startButton = QtWidgets.QPushButton(self.widget_11)
        self.startButton.setMinimumSize(QtCore.QSize(150, 150))
        self.startButton.setMaximumSize(QtCore.QSize(150, 150))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color: rgb(76, 175, 80);\n"
"border-radius:75px;\n"
"color: rgb(255, 255, 255);")
        self.startButton.setObjectName("startButton")
        self.gridLayout_3.addWidget(self.startButton, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.widget_11)
        self.horizontalLayout_3.addWidget(self.widget_8)
        self.horizontalLayout_3.setStretch(0, 7)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.addWidget(self.widget_7)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 9)
        self.pageStackedWidget.addWidget(self.sportPage)
        self.settingsPage = QtWidgets.QWidget()
        self.settingsPage.setObjectName("settingsPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.settingsPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_14 = QtWidgets.QWidget(self.settingsPage)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_14)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.widget_14)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("/*color: rgb(129, 131, 133);*/")
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.settingsPage)
        self.widget_15.setStyleSheet("#widget_15{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_22 = QtWidgets.QWidget(self.widget_15)
        self.widget_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_22.setStyleSheet("#widget_22{\n"
"    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 10px solid qlineargradient(x0:0, x1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-bottom: 10px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  #ececef);\n"
"    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(243, 245, 253);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"    padding-left: 15px;\n"
"}")
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_6 = QtWidgets.QLabel(self.widget_22)
        self.label_6.setMinimumSize(QtCore.QSize(0, 54))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 54))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(129, 131, 133);\n"
"margin-left: 10px;")
        self.label_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_13.addWidget(self.label_6)
        self.widget_26 = QtWidgets.QWidget(self.widget_22)
        self.widget_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_26.setStyleSheet("#widget_26{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(243, 245, 253);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"    padding-left: 15px;\n"
"}")
        self.widget_26.setObjectName("widget_26")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_26)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 0, 0, 1, 1)
        self.widget_27 = QtWidgets.QWidget(self.widget_26)
        self.widget_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_27.setStyleSheet("#widget_27{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_27.setObjectName("widget_27")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_27)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.registerUsernameLineEdit = QtWidgets.QLineEdit(self.widget_27)
        self.registerUsernameLineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.registerUsernameLineEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerUsernameLineEdit.setFont(font)
        self.registerUsernameLineEdit.setStyleSheet("")
        self.registerUsernameLineEdit.setText("")
        self.registerUsernameLineEdit.setClearButtonEnabled(True)
        self.registerUsernameLineEdit.setObjectName("registerUsernameLineEdit")
        self.gridLayout_9.addWidget(self.registerUsernameLineEdit, 0, 0, 1, 1)
        self.registerUsernameLineEdit_2 = QtWidgets.QLineEdit(self.widget_27)
        self.registerUsernameLineEdit_2.setMinimumSize(QtCore.QSize(0, 50))
        self.registerUsernameLineEdit_2.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerUsernameLineEdit_2.setFont(font)
        self.registerUsernameLineEdit_2.setStyleSheet("")
        self.registerUsernameLineEdit_2.setText("")
        self.registerUsernameLineEdit_2.setClearButtonEnabled(True)
        self.registerUsernameLineEdit_2.setObjectName("registerUsernameLineEdit_2")
        self.gridLayout_9.addWidget(self.registerUsernameLineEdit_2, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_27)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(253, 183, 84);\n"
"    border-radius:20px;\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 2, 0, 1, 1)
        self.gridLayout_11.addWidget(self.widget_27, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 0, 2, 1, 1)
        self.verticalLayout_13.addWidget(self.widget_26)
        self.gridLayout_2.addWidget(self.widget_22, 0, 0, 1, 1)
        self.widget_23 = QtWidgets.QWidget(self.widget_15)
        self.widget_23.setStyleSheet("#widget_23{\n"
"    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 10px solid qlineargradient(x0:0, x1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-bottom: 10px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  #ececef);\n"
"    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_8 = QtWidgets.QLabel(self.widget_23)
        self.label_8.setMinimumSize(QtCore.QSize(0, 54))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 54))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(129, 131, 133);\n"
"margin-left: 10px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_14.addWidget(self.label_8)
        self.widget_28 = QtWidgets.QWidget(self.widget_23)
        self.widget_28.setStyleSheet("#widget_28{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: rgb(243, 245, 253);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(243, 245, 253);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: gray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    border-image: url(./window/icons/arrow_down.svg);\n"
"}")
        self.widget_28.setObjectName("widget_28")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget_28)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem10 = QtWidgets.QSpacerItem(116, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 0, 0, 1, 1)
        self.widget_29 = QtWidgets.QWidget(self.widget_28)
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_29.setStyleSheet("#widget_29{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_29.setObjectName("widget_29")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.widget_29)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.comboBox = QtWidgets.QComboBox(self.widget_29)
        self.comboBox.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_17.addWidget(self.comboBox, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_29)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color: rgb(253, 183, 84);\n"
"    border-radius:20px;\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_17.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_29)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_17.addWidget(self.label_15, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.widget_29, 0, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_18.addItem(spacerItem11, 0, 2, 1, 1)
        self.verticalLayout_14.addWidget(self.widget_28)
        self.verticalLayout_14.setStretch(0, 1)
        self.gridLayout_2.addWidget(self.widget_23, 0, 1, 1, 1)
        self.widget_24 = QtWidgets.QWidget(self.widget_15)
        self.widget_24.setStyleSheet("#widget_24{\n"
"    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 10px solid qlineargradient(x0:0, x1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-bottom: 10px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  #ececef);\n"
"    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_24)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_9 = QtWidgets.QLabel(self.widget_24)
        self.label_9.setMinimumSize(QtCore.QSize(0, 54))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 54))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(129, 131, 133);\n"
"margin-left: 10px;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_15.addWidget(self.label_9)
        self.widget_30 = QtWidgets.QWidget(self.widget_24)
        self.widget_30.setStyleSheet("#widget_30{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(243, 245, 253);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"    padding-left: 15px;\n"
"}")
        self.widget_30.setObjectName("widget_30")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.widget_30)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_15.addItem(spacerItem12, 0, 0, 1, 1)
        self.widget_31 = QtWidgets.QWidget(self.widget_30)
        self.widget_31.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_31.setStyleSheet("#widget_31{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_31.setObjectName("widget_31")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.widget_31)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.registerUsernameLineEdit_5 = QtWidgets.QLineEdit(self.widget_31)
        self.registerUsernameLineEdit_5.setMinimumSize(QtCore.QSize(0, 50))
        self.registerUsernameLineEdit_5.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerUsernameLineEdit_5.setFont(font)
        self.registerUsernameLineEdit_5.setStyleSheet("")
        self.registerUsernameLineEdit_5.setText("")
        self.registerUsernameLineEdit_5.setMaxLength(3)
        self.registerUsernameLineEdit_5.setClearButtonEnabled(True)
        self.registerUsernameLineEdit_5.setObjectName("registerUsernameLineEdit_5")
        self.gridLayout_14.addWidget(self.registerUsernameLineEdit_5, 0, 0, 1, 1)
        self.registerUsernameLineEdit_6 = QtWidgets.QLineEdit(self.widget_31)
        self.registerUsernameLineEdit_6.setMinimumSize(QtCore.QSize(0, 50))
        self.registerUsernameLineEdit_6.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerUsernameLineEdit_6.setFont(font)
        self.registerUsernameLineEdit_6.setStyleSheet("")
        self.registerUsernameLineEdit_6.setText("")
        self.registerUsernameLineEdit_6.setMaxLength(3)
        self.registerUsernameLineEdit_6.setClearButtonEnabled(True)
        self.registerUsernameLineEdit_6.setObjectName("registerUsernameLineEdit_6")
        self.gridLayout_14.addWidget(self.registerUsernameLineEdit_6, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_31)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_6.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color: rgb(253, 183, 84);\n"
"    border-radius:20px;\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_14.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.gridLayout_15.addWidget(self.widget_31, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_15.addItem(spacerItem13, 0, 2, 1, 1)
        self.verticalLayout_15.addWidget(self.widget_30)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 9)
        self.gridLayout_2.addWidget(self.widget_24, 1, 0, 1, 1)
        self.widget_25 = QtWidgets.QWidget(self.widget_15)
        self.widget_25.setStyleSheet("#widget_25{\n"
"    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 10px solid qlineargradient(x0:0, x1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-bottom: 10px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  #ececef);\n"
"    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_25.setObjectName("widget_25")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_25)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.widget_25)
        self.label_13.setMinimumSize(QtCore.QSize(0, 54))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 54))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(129, 131, 133);\n"
"margin-left: 10px;")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.widget_32 = QtWidgets.QWidget(self.widget_25)
        self.widget_32.setStyleSheet("#widget_32{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(243, 245, 253);\n"
"    border-radius:10px;\n"
"    border:none;\n"
"    padding-left: 15px;\n"
"}")
        self.widget_32.setObjectName("widget_32")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.widget_32)
        self.gridLayout_16.setObjectName("gridLayout_16")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_16.addItem(spacerItem14, 0, 0, 1, 1)
        self.widget_33 = QtWidgets.QWidget(self.widget_32)
        self.widget_33.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_33.setStyleSheet("#widget_33{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.widget_33.setObjectName("widget_33")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_33)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.registerUsernameLineEdit_8 = QtWidgets.QLineEdit(self.widget_33)
        self.registerUsernameLineEdit_8.setMinimumSize(QtCore.QSize(0, 50))
        self.registerUsernameLineEdit_8.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerUsernameLineEdit_8.setFont(font)
        self.registerUsernameLineEdit_8.setStyleSheet("")
        self.registerUsernameLineEdit_8.setText("")
        self.registerUsernameLineEdit_8.setMaxLength(3)
        self.registerUsernameLineEdit_8.setClearButtonEnabled(True)
        self.registerUsernameLineEdit_8.setObjectName("registerUsernameLineEdit_8")
        self.gridLayout_13.addWidget(self.registerUsernameLineEdit_8, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_33)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_7.setMaximumSize(QtCore.QSize(350, 16777215))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color: rgb(253, 183, 84);\n"
"    border-radius:20px;\n"
"    border:none;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_13.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_33)
        self.label_14.setMinimumSize(QtCore.QSize(0, 0))
        self.label_14.setMaximumSize(QtCore.QSize(0, 45))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_13.addWidget(self.label_14, 2, 0, 1, 1)
        self.gridLayout_16.addWidget(self.widget_33, 0, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_16.addItem(spacerItem15, 0, 2, 1, 1)
        self.verticalLayout_16.addWidget(self.widget_32)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 9)
        self.gridLayout_2.addWidget(self.widget_25, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 5)
        self.gridLayout_2.setColumnStretch(1, 5)
        self.gridLayout_2.setRowStretch(0, 5)
        self.gridLayout_2.setRowStretch(1, 5)
        self.verticalLayout_2.addWidget(self.widget_15)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 9)
        self.pageStackedWidget.addWidget(self.settingsPage)
        self.horizontalLayout.addWidget(self.pageStackedWidget)
        self.horizontalLayout.setStretch(0, 2)
        Index_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Index_Window)
        self.pageStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Index_Window)

    def retranslateUi(self, Index_Window):
        _translate = QtCore.QCoreApplication.translate
        Index_Window.setWindowTitle(_translate("Index_Window", "莫狗健身"))
        __sortingEnabled = self.pageListWidget.isSortingEnabled()
        self.pageListWidget.setSortingEnabled(False)
        item = self.pageListWidget.item(0)
        item.setText(_translate("Index_Window", "首页"))
        item = self.pageListWidget.item(1)
        item.setText(_translate("Index_Window", "开始运动"))
        item = self.pageListWidget.item(2)
        item.setText(_translate("Index_Window", "运动记录"))
        item = self.pageListWidget.item(3)
        item.setText(_translate("Index_Window", "设置"))
        self.pageListWidget.setSortingEnabled(__sortingEnabled)
        self.exitButton.setText(_translate("Index_Window", " 退出"))
        self.label_11.setText(_translate("Index_Window", "首页"))
        self.label_12.setText(_translate("Index_Window", "运动记录"))
        self.label_2.setText(_translate("Index_Window", "运动类型"))
        self.history_query_squat_pushButton.setText(_translate("Index_Window", "深蹲"))
        self.history_query_dumbbell_pushButton.setText(_translate("Index_Window", "哑铃"))
        self.history_query_push_pushButton.setText(_translate("Index_Window", "俯卧撑"))
        self.history_query_all_pushButton.setText(_translate("Index_Window", "全部"))
        self.history_query_jumpingJacks_pushButton.setText(_translate("Index_Window", "开合跳"))
        self.history_query_chinning_pushButton.setText(_translate("Index_Window", "引体向上"))
        self.label_3.setText(_translate("Index_Window", "日期选择"))
        self.history_reset_pushButton.setText(_translate("Index_Window", "重置"))
        self.history_sift_pushButton.setText(_translate("Index_Window", "筛选"))
        self.label_4.setText(_translate("Index_Window", "开始运动"))
        self.pushChoice_Button.setText(_translate("Index_Window", "俯卧撑"))
        self.chinningChoiceButton.setText(_translate("Index_Window", "引体向上"))
        self.dumbbellChoiceButton.setText(_translate("Index_Window", "哑铃"))
        self.pushButton_8.setText(_translate("Index_Window", "暂未开放"))
        self.pushButton_9.setText(_translate("Index_Window", "暂未开放"))
        self.pushButton_10.setText(_translate("Index_Window", "暂未开放"))
        self.pushButton_11.setText(_translate("Index_Window", "暂未开放"))
        self.squatChoice_Button.setText(_translate("Index_Window", "深蹲"))
        self.jumpingJacksChoice_Button.setText(_translate("Index_Window", "开合跳"))
        self.leftTime_Label.setText(_translate("Index_Window", "0 分 10 秒"))
        self.label_5.setText(_translate("Index_Window", "项目"))
        self.item_Label.setText(_translate("Index_Window", "俯卧撑"))
        self.label_7.setText(_translate("Index_Window", "时间"))
        self.rightTime_Label.setText(_translate("Index_Window", "0 分 10 秒"))
        self.startButton.setText(_translate("Index_Window", "开始运动"))
        self.label_10.setText(_translate("Index_Window", "设置"))
        self.label_6.setText(_translate("Index_Window", "修改密码"))
        self.registerUsernameLineEdit.setPlaceholderText(_translate("Index_Window", "需要重设的密码"))
        self.registerUsernameLineEdit_2.setPlaceholderText(_translate("Index_Window", "再次输入需要重设的密码"))
        self.pushButton.setText(_translate("Index_Window", "提交"))
        self.label_8.setText(_translate("Index_Window", "修改性别"))
        self.comboBox.setPlaceholderText(_translate("Index_Window", "请选择性别"))
        self.comboBox.setItemText(0, _translate("Index_Window", "男"))
        self.comboBox.setItemText(1, _translate("Index_Window", "女"))
        self.pushButton_3.setText(_translate("Index_Window", "提交"))
        self.label_9.setText(_translate("Index_Window", "修改身高体重"))
        self.registerUsernameLineEdit_5.setPlaceholderText(_translate("Index_Window", "请输入身高"))
        self.registerUsernameLineEdit_6.setPlaceholderText(_translate("Index_Window", "请输入体重"))
        self.pushButton_6.setText(_translate("Index_Window", "提交"))
        self.label_13.setText(_translate("Index_Window", "修改昵称"))
        self.registerUsernameLineEdit_8.setPlaceholderText(_translate("Index_Window", "请输入昵称"))
        self.pushButton_7.setText(_translate("Index_Window", "提交"))
