# Form implementation generated from reading ui file 'index_history_item.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HistoryItem(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, HistoryItem):
        HistoryItem.setObjectName("HistoryItem")
        HistoryItem.resize(816, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred,
                                           QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HistoryItem.sizePolicy().hasHeightForWidth())
        HistoryItem.setSizePolicy(sizePolicy)
        HistoryItem.setMinimumSize(QtCore.QSize(0, 150))
        HistoryItem.setMaximumSize(QtCore.QSize(16777215, 150))
        HistoryItem.setStyleSheet("color: rgb(255, 255, 255);\n"
                                  "height: 150px;\n"
                                  "border-radius:5px;\n"
                                  "width:150px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(HistoryItem)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(HistoryItem)
        self.widget_2.setStyleSheet("QWidget{\n"
                                    "    background-color: rgb(255, 255, 255);\n"
                                    "    border-top-right-radius: 0px;\n"
                                    "    border-bottom-right-radius: 0px;\n"
                                    "}\n"
                                    "\n"
                                    "QLabel{\n"
                                    "    color: rgb(0, 0, 0);\n"
                                    "}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setStyleSheet("#widget_4{\n"
                                    "    border-top:1px solid rgb(189, 189, 189);\n"
                                    "    border-bottom:1px solid rgb(189, 189, 189);\n"
                                    "    border-left:1px solid rgb(189, 189, 189);\n"
                                    "}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(129, 131, 133);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sport_name_label = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sport_name_label.setFont(font)
        self.sport_name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sport_name_label.setObjectName("sport_name_label")
        self.verticalLayout.addWidget(self.sport_name_label)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setStyleSheet("#widget_5{\n"
                                    "    border-left:1px dashed rgb(189, 189, 189);\n"
                                    "    border-radius:0px;\n"
                                    "    border-top:1px solid rgb(189, 189, 189);\n"
                                    "    border-bottom:1px solid rgb(189, 189, 189);\n"
                                    "}")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(129, 131, 133);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.count_label = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.count_label.setFont(font)
        self.count_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.count_label.setObjectName("count_label")
        self.verticalLayout_2.addWidget(self.count_label)
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setStyleSheet("#widget_6{\n"
                                    "    border-left:1px dashed rgb(189, 189, 189);\n"
                                    "    border-radius:0px;\n"
                                    "    border-top:1px solid rgb(189, 189, 189);\n"
                                    "    border-bottom:1px solid rgb(189, 189, 189);\n"
                                    "}")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(129, 131, 133);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.sport_time_label = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.sport_time_label.setFont(font)
        self.sport_time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sport_time_label.setObjectName("sport_time_label")
        self.verticalLayout_3.addWidget(self.sport_time_label)
        self.horizontalLayout_2.addWidget(self.widget_6)
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setMinimumSize(QtCore.QSize(210, 0))
        self.widget_7.setStyleSheet("#widget_7{\n"
                                    "    border-left:1px dashed rgb(189, 189, 189);\n"
                                    "    border-radius:0px;\n"
                                    "    border-top:1px solid rgb(189, 189, 189);\n"
                                    "    border-bottom:1px solid rgb(189, 189, 189);\n"
                                    "}")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(129, 131, 133);")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.start_time_label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_time_label.setFont(font)
        self.start_time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.start_time_label.setWordWrap(True)
        self.start_time_label.setObjectName("start_time_label")
        self.verticalLayout_4.addWidget(self.start_time_label)
        self.horizontalLayout_2.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(HistoryItem)
        self.widget_3.setMinimumSize(QtCore.QSize(50, 150))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_3.setStyleSheet("border-top-left-radius: 0px;\n"
                                    "border-bottom-left-radius: 0px;\n"
                                    "border-top-right-radius: 5px;\n"
                                    "border-bottom-right-radius:5px;\n"
                                    "background-color: rgb(50, 191, 209);\n"
                                    "width:150px;\n"
                                    "margin-bottom:10px;")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout.addWidget(self.widget_3)
        self.horizontalLayout.setStretch(0, 9)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(HistoryItem)
        QtCore.QMetaObject.connectSlotsByName(HistoryItem)

    def retranslateUi(self, HistoryItem):
        _translate = QtCore.QCoreApplication.translate
        HistoryItem.setWindowTitle(_translate("HistoryItem", "Form"))
        self.label.setText(_translate("HistoryItem", "运动项目"))
        self.sport_name_label.setText(_translate("HistoryItem", "引体向上"))
        self.label_2.setText(_translate("HistoryItem", "数量"))
        self.count_label.setText(_translate("HistoryItem", "60"))
        self.label_3.setText(_translate("HistoryItem", "运动时间"))
        self.sport_time_label.setText(_translate("HistoryItem", "10 s"))
        self.label_4.setText(_translate("HistoryItem", "开始时间"))
        self.start_time_label.setText(_translate("HistoryItem", "2023-01-10 11:27:57"))
