# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login_window(object):
    def setupUi(self, Login_window):
        Login_window.setObjectName("Login_window")
        Login_window.resize(988, 521)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./window/icons/dog.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Login_window.setWindowIcon(icon)
        self.stackedWidget = QtWidgets.QStackedWidget(Login_window)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 988, 521))
        self.stackedWidget.setObjectName("stackedWidget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.LoginButton = QtWidgets.QPushButton(self.login_page)
        self.LoginButton.setGeometry(QtCore.QRect(680, 370, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoginButton.setFont(font)
        self.LoginButton.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(107,152,246);\n"
                                       "    border-radius:20px;\n"
                                       "    border:none;\n"
                                       "    color: rgb(255, 255, 255);\n"
                                       "    outline:0px;\n"
                                       "}")
        self.LoginButton.setObjectName("LoginButton")
        self.label_8 = QtWidgets.QLabel(self.login_page)
        self.label_8.setGeometry(QtCore.QRect(690, 320, 25, 25))
        self.label_8.setStyleSheet("border-image: url(./window/icons/lock.svg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.toRegister_Button = QtWidgets.QPushButton(self.login_page)
        self.toRegister_Button.setGeometry(QtCore.QRect(830, 420, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toRegister_Button.setFont(font)
        self.toRegister_Button.setStyleSheet("QPushButton{\n"
                                             "    background-color: rgb(255, 255, 255);\n"
                                             "    border:0px;\n"
                                             "    color: rgb(56, 92, 188);\n"
                                             "}")
        self.toRegister_Button.setObjectName("toRegister_Button")
        self.label_2 = QtWidgets.QLabel(self.login_page)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 540, 342))
        self.label_2.setStyleSheet("border-image: url(./window/images/login_bg.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.login_page)
        self.UsernameLineEdit.setGeometry(QtCore.QRect(680, 253, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.UsernameLineEdit.setFont(font)
        self.UsernameLineEdit.setStyleSheet("QLineEdit{\n"
                                            "    background-color: rgb(243, 245, 253);\n"
                                            "    border-radius:20px;\n"
                                            "    border:none;\n"
                                            "    padding-left: 38px;\n"
                                            "}")
        self.UsernameLineEdit.setText("")
        self.UsernameLineEdit.setClearButtonEnabled(True)
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.label_7 = QtWidgets.QLabel(self.login_page)
        self.label_7.setGeometry(QtCore.QRect(690, 260, 25, 25))
        self.label_7.setStyleSheet("border-image: url(./window/icons/user.svg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.closeButton = QtWidgets.QPushButton(self.login_page)
        self.closeButton.setGeometry(QtCore.QRect(920, 10, 61, 31))
        self.closeButton.setStyleSheet("QPushButton{\n"
                                       "    border: none;\n"
                                       "    border-top-right-radius:10px;\n"
                                       "    border-bottom-left-radius:10px;\n"
                                       "    outline:0px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(250,76,62);\n"
                                       "}")
        self.closeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./window/icons/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setIconSize(QtCore.QSize(25, 25))
        self.closeButton.setObjectName("closeButton")
        self.rememberPwd_checkBox = QtWidgets.QCheckBox(self.login_page)
        self.rememberPwd_checkBox.setGeometry(QtCore.QRect(685, 419, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rememberPwd_checkBox.setFont(font)
        self.rememberPwd_checkBox.setStyleSheet("QCheckBox{\n"
                                                "    \n"
                                                "}\n"
                                                "QCheckBox::indicator{/*选择框尺寸*/\n"
                                                "    background-color: rgb(255, 255, 255);\n"
                                                "    border: 1px solid #385CBC;\n"
                                                "    width: 11px;\n"
                                                "    height: 11px;\n"
                                                "    border-radius:2px;\n"
                                                "}\n"
                                                "\n"
                                                "QCheckBox::indicator:checked {\n"
                                                "    image: url(./window/icons/check.svg);\n"
                                                "}\n"
                                                "")
        self.rememberPwd_checkBox.setObjectName("rememberPwd_checkBox")
        self.errorLabel = QtWidgets.QLabel(self.login_page)
        self.errorLabel.setGeometry(QtCore.QRect(690, 450, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorLabel.setFont(font)
        self.errorLabel.setStyleSheet("color: rgb(255, 70, 73);")
        self.errorLabel.setText("")
        self.errorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.errorLabel.setObjectName("errorLabel")
        self.label_10 = QtWidgets.QLabel(self.login_page)
        self.label_10.setGeometry(QtCore.QRect(40, 38, 40, 40))
        self.label_10.setStyleSheet("border-image: url(./window/icons/bone.svg);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.PwdLineEdit = QtWidgets.QLineEdit(self.login_page)
        self.PwdLineEdit.setGeometry(QtCore.QRect(680, 313, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.PwdLineEdit.setFont(font)
        self.PwdLineEdit.setStyleSheet("QLineEdit{\n"
                                       "    background-color: rgb(243, 245, 253);\n"
                                       "    border-radius:20px;\n"
                                       "    border:none;\n"
                                       "    padding-left: 38px;\n"
                                       "}")
        self.PwdLineEdit.setText("")
        self.PwdLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.PwdLineEdit.setClearButtonEnabled(True)
        self.PwdLineEdit.setObjectName("PwdLineEdit")
        self.label_9 = QtWidgets.QLabel(self.login_page)
        self.label_9.setGeometry(QtCore.QRect(90, 30, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(56, 92, 188);")
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.login_page)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 10, 971, 501))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.login_page)
        self.label_3.setGeometry(QtCore.QRect(710, 110, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.login_page)
        self.label_6.setGeometry(QtCore.QRect(715, 180, 148, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.login_page)
        self.label_4.setGeometry(QtCore.QRect(670, 120, 50, 50))
        self.label_4.setStyleSheet("border-image: url(./window/icons/js_l.svg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.login_page)
        self.label_5.setGeometry(QtCore.QRect(860, 120, 50, 50))
        self.label_5.setStyleSheet("border-image: url(./window/icons/js_r.svg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label.raise_()
        self.LoginButton.raise_()
        self.toRegister_Button.raise_()
        self.label_2.raise_()
        self.UsernameLineEdit.raise_()
        self.label_7.raise_()
        self.closeButton.raise_()
        self.rememberPwd_checkBox.raise_()
        self.label_10.raise_()
        self.PwdLineEdit.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.errorLabel.raise_()
        self.stackedWidget.addWidget(self.login_page)
        self.register_page = QtWidgets.QWidget()
        self.register_page.setObjectName("register_page")
        self.label_11 = QtWidgets.QLabel(self.register_page)
        self.label_11.setEnabled(True)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 971, 501))
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border-radius:10px;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.toLogin_Button = QtWidgets.QPushButton(self.register_page)
        self.toLogin_Button.setGeometry(QtCore.QRect(10, 10, 70, 40))
        self.toLogin_Button.setStyleSheet("QPushButton{\n"
                                          "    border: none;\n"
                                          "    border-top-left-radius:10px;\n"
                                          "    border-bottom-right-radius:10px;\n"
                                          "    outline:0px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton:hover{\n"
                                          "    background-color: #D6D6D6;\n"
                                          "}")
        self.toLogin_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./window/icons/back.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toLogin_Button.setIcon(icon2)
        self.toLogin_Button.setIconSize(QtCore.QSize(25, 25))
        self.toLogin_Button.setObjectName("toLogin_Button")
        self.label_12 = QtWidgets.QLabel(self.register_page)
        self.label_12.setGeometry(QtCore.QRect(529, 150, 401, 331))
        self.label_12.setStyleSheet("border-image: url(./window/images/approve request.svg);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.widget = QtWidgets.QWidget(self.register_page)
        self.widget.setGeometry(QtCore.QRect(110, 50, 380, 451))
        self.widget.setStyleSheet("#widget{\n"
                                  "    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
                                  "    border-left: 10px solid qlineargradient(x0:0, x1:1,stop: 0 #ececef, stop: 1 white);\n"
                                  "    border-bottom: 10px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  #ececef);\n"
                                  "    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
                                  "}\n"
                                  "\n"
                                  "QLineEdit{\n"
                                  "    background-color: rgb(243, 245, 253);\n"
                                  "    border-radius:10px;\n"
                                  "    border:none;\n"
                                  "    padding-left: 15px;\n"
                                  "}\n"
                                  "\n"
                                  "QGroupBox{\n"
                                  "    background-color: rgb(243, 245, 253);\n"
                                  "    border-radius:10px;\n"
                                  "    border:none;\n"
                                  "    font-size: 15px;\n"
                                  "    padding-left: 15px;\n"
                                  "}")
        self.widget.setObjectName("widget")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(120, 20, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(56, 92, 188);")
        self.label_13.setObjectName("label_13")
        self.registerButton = QtWidgets.QPushButton(self.widget)
        self.registerButton.setGeometry(QtCore.QRect(55, 360, 270, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("QPushButton{\n"
                                          "    background-color: rgb(253, 183, 84);\n"
                                          "    border-radius:20px;\n"
                                          "    border:none;\n"
                                          "    color: rgb(255, 255, 255);\n"
                                          "}")
        self.registerButton.setObjectName("registerButton")
        self.registerUsernameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.registerUsernameLineEdit.setGeometry(QtCore.QRect(55, 90, 270, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerUsernameLineEdit.setFont(font)
        self.registerUsernameLineEdit.setStyleSheet("")
        self.registerUsernameLineEdit.setText("")
        self.registerUsernameLineEdit.setClearButtonEnabled(True)
        self.registerUsernameLineEdit.setObjectName("registerUsernameLineEdit")
        self.registerPasswordLineEdit = QtWidgets.QLineEdit(self.widget)
        self.registerPasswordLineEdit.setGeometry(QtCore.QRect(55, 140, 270, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerPasswordLineEdit.setFont(font)
        self.registerPasswordLineEdit.setStyleSheet("")
        self.registerPasswordLineEdit.setText("")
        self.registerPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.registerPasswordLineEdit.setClearButtonEnabled(True)
        self.registerPasswordLineEdit.setObjectName("registerPasswordLineEdit")
        self.registerNicknameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.registerNicknameLineEdit.setGeometry(QtCore.QRect(55, 190, 270, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerNicknameLineEdit.setFont(font)
        self.registerNicknameLineEdit.setStyleSheet("")
        self.registerNicknameLineEdit.setText("")
        self.registerNicknameLineEdit.setClearButtonEnabled(True)
        self.registerNicknameLineEdit.setObjectName("registerNicknameLineEdit")
        self.registerHeightLineEdit = QtWidgets.QLineEdit(self.widget)
        self.registerHeightLineEdit.setGeometry(QtCore.QRect(55, 290, 130, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerHeightLineEdit.setFont(font)
        self.registerHeightLineEdit.setStyleSheet("")
        self.registerHeightLineEdit.setText("")
        self.registerHeightLineEdit.setClearButtonEnabled(True)
        self.registerHeightLineEdit.setObjectName("registerHeightLineEdit")
        self.registerWeightLineEdit = QtWidgets.QLineEdit(self.widget)
        self.registerWeightLineEdit.setGeometry(QtCore.QRect(195, 290, 130, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.registerWeightLineEdit.setFont(font)
        self.registerWeightLineEdit.setStyleSheet("")
        self.registerWeightLineEdit.setText("")
        self.registerWeightLineEdit.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.registerWeightLineEdit.setClearButtonEnabled(True)
        self.registerWeightLineEdit.setObjectName("registerWeightLineEdit")
        self.registerErrorLabel = QtWidgets.QLabel(self.widget)
        self.registerErrorLabel.setGeometry(QtCore.QRect(89, 410, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.registerErrorLabel.setFont(font)
        self.registerErrorLabel.setStyleSheet("color: rgb(255, 70, 73);")
        self.registerErrorLabel.setText("")
        self.registerErrorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.registerErrorLabel.setObjectName("registerErrorLabel")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(55, 240, 270, 41))
        self.groupBox.setStyleSheet("#groupBox{\n"
                                    "padding:0px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton{\n"
                                    "    background-color: transparent;\n"
                                    "}\n"
                                    "QPushButton::checked {\n"
                                    "    background-color: rgb(85, 175, 252);\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registerManPushButton = QtWidgets.QPushButton(self.groupBox)
        self.registerManPushButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registerManPushButton.setFont(font)
        self.registerManPushButton.setStyleSheet("border-top-left-radius:10px;\n"
                                                 "border-bottom-left-radius:10px;")
        self.registerManPushButton.setCheckable(True)
        self.registerManPushButton.setChecked(True)
        self.registerManPushButton.setAutoExclusive(True)
        self.registerManPushButton.setObjectName("registerManPushButton")
        self.horizontalLayout.addWidget(self.registerManPushButton)
        self.registerWomanPushButton = QtWidgets.QPushButton(self.groupBox)
        self.registerWomanPushButton.setMinimumSize(QtCore.QSize(0, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registerWomanPushButton.setFont(font)
        self.registerWomanPushButton.setStyleSheet("border-top-right-radius:10px;\n"
                                                   "border-bottom-right-radius:10px;")
        self.registerWomanPushButton.setCheckable(True)
        self.registerWomanPushButton.setAutoExclusive(True)
        self.registerWomanPushButton.setObjectName("registerWomanPushButton")
        self.horizontalLayout.addWidget(self.registerWomanPushButton)
        self.stackedWidget.addWidget(self.register_page)

        self.retranslateUi(Login_window)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login_window)

    def retranslateUi(self, Login_window):
        _translate = QtCore.QCoreApplication.translate
        Login_window.setWindowTitle(_translate("Login_window", "莫狗健身"))
        self.LoginButton.setText(_translate("Login_window", "登录"))
        self.toRegister_Button.setText(_translate("Login_window", "立即注册？"))
        self.UsernameLineEdit.setPlaceholderText(_translate("Login_window", "用户名"))
        self.rememberPwd_checkBox.setText(_translate("Login_window", "记住密码"))
        self.PwdLineEdit.setPlaceholderText(_translate("Login_window", "密码"))
        self.label_9.setText(_translate("Login_window", "欢迎使用莫狗AI智能健身系统 :)"))
        self.label_3.setText(_translate("Login_window", "莫狗健身"))
        self.label_6.setText(_translate("Login_window", "不做细狗，从我做起"))
        self.label_13.setText(_translate("Login_window", "注册莫狗健身 :)"))
        self.registerButton.setText(_translate("Login_window", "注册"))
        self.registerUsernameLineEdit.setPlaceholderText(_translate("Login_window", "用户名"))
        self.registerPasswordLineEdit.setPlaceholderText(_translate("Login_window", "密码"))
        self.registerNicknameLineEdit.setPlaceholderText(_translate("Login_window", "昵称"))
        self.registerHeightLineEdit.setPlaceholderText(_translate("Login_window", "身高(厘米)"))
        self.registerWeightLineEdit.setPlaceholderText(_translate("Login_window", "体重(斤)"))
        self.registerManPushButton.setText(_translate("Login_window", "男"))
        self.registerWomanPushButton.setText(_translate("Login_window", "女"))
