# Form implementation generated from reading ui file 'start_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_startWidget(QtWidgets):
    def setupUi(self, startWidget):
        startWidget.setObjectName("startWidget")
        startWidget.resize(532, 281)
        self.widget = QtWidgets.QWidget(startWidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 532, 281))
        self.widget.setStyleSheet("background-color: rgba(34, 31, 31, 0.6);\n"
                                  "border-radius:40px;")
        self.widget.setObjectName("widget")
        self.startButton = QtWidgets.QPushButton(self.widget)
        self.startButton.setGeometry(QtCore.QRect(340, 210, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color: rgb(251, 95, 56);\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "border-radius:20px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./window/icons/play.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.startButton.setIcon(icon)
        self.startButton.setIconSize(QtCore.QSize(20, 20))
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(376, 49, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setKerning(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(117, 50, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setKerning(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "background-color: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.timeLabel = QtWidgets.QLabel(self.widget)
        self.timeLabel.setGeometry(QtCore.QRect(290, 100, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("background-color: transparent;\n"
                                     "color: rgb(255, 255, 255);")
        self.timeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.itemLabel = QtWidgets.QLabel(self.widget)
        self.itemLabel.setGeometry(QtCore.QRect(40, 100, 200, 60))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.itemLabel.setFont(font)
        self.itemLabel.setStyleSheet("background-color: transparent;\n"
                                     "color: rgb(255, 255, 255);")
        self.itemLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.itemLabel.setObjectName("itemLabel")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(268, 20, 2, 181))
        self.label_8.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.exitButton = QtWidgets.QPushButton(self.widget)
        self.exitButton.setGeometry(QtCore.QRect(80, 210, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("background-color: rgb(49, 51, 55);\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "border-radius:20px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./window/icons/exit.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.exitButton.setIcon(icon1)
        self.exitButton.setIconSize(QtCore.QSize(25, 25))
        self.exitButton.setObjectName("exitButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(349, 50, 30, 30))
        self.label_2.setStyleSheet("background-color: transparent;\n"
                                   "border-image: url(./window/icons/clock.svg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(87, 48, 35, 35))
        self.label_3.setStyleSheet("background-color: transparent;\n"
                                   "border-image: url(./window/icons/js.svg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(startWidget)
        QtCore.QMetaObject.connectSlotsByName(startWidget)

    def retranslateUi(self, startWidget):
        _translate = QtCore.QCoreApplication.translate
        startWidget.setWindowTitle(_translate("startWidget", "Form"))
        self.startButton.setText(_translate("startWidget", " 开始"))
        self.label.setText(_translate("startWidget", "时间"))
        self.label_4.setText(_translate("startWidget", "项目"))
        self.timeLabel.setText(_translate("startWidget", "60 s"))
        self.itemLabel.setText(_translate("startWidget", "引体向上"))
        self.exitButton.setText(_translate("startWidget", " 退出"))
